CREATE TABLE blogUsers (
    USERID SERIAL PRIMARY KEY,
    USERNAME TEXT,
    EMAIL TEXT,
    UPASS TEXT
)

CREATE TABLE blogs (
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(256),
    CAT TEXT,
    TAGS TEXT [],
    CONTENT TEXT,
    PUBLISHED BOOLEAN DEFAULT FALSE,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LASTEDIT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
